#! /bin/bash

METHOD="$1"
IMAGE="$2"
TAG="$3"

if [ "$METHOD" = "build" ]; then

  # base build <image> <tag>
  docker build -t base-${IMAGE}:${TAG} -f ${IMAGE}/${TAG}/${IMAGE}.dockerfile ${IMAGE}/${TAG}/

elif [ "$METHOD" = "tag" ]; then

  # base push <image> <tag>
  docker tag base-${IMAGE}:${TAG} awmly/base-${IMAGE}:${TAG}

elif [ "$METHOD" = "push" ]; then

  # base push <image> <tag>
  docker push awmly/base-${IMAGE}:${TAG}

fi

